2019-05-28 16:45:38,785 start_driver.py[line:26] INFO: start app...
2019-05-28 16:56:25,598 start_driver.py[line:26] INFO: start app...
2019-05-28 17:57:04,733 start_driver.py[line:26] INFO: start app...
2019-05-28 17:57:42,403 common_func.py[line:53] ERROR: No element found
2019-05-29 11:13:20,719 start_driver.py[line:26] INFO: start app...
2019-05-29 11:14:06,841 common_func.py[line:53] ERROR: No element found
2019-05-29 11:15:03,718 start_driver.py[line:26] INFO: start app...
2019-05-29 11:15:51,180 common_func.py[line:53] ERROR: No element found
2019-05-29 11:17:22,106 start_driver.py[line:26] INFO: start app...
2019-05-29 11:19:35,958 start_driver.py[line:26] INFO: start app...
2019-05-29 11:26:32,478 start_driver.py[line:26] INFO: start app...
2019-05-29 12:40:51,976 start_driver.py[line:26] INFO: start app...
2019-05-29 13:43:15,598 start_driver.py[line:26] INFO: start app...
2019-05-29 13:45:11,652 start_driver.py[line:26] INFO: start app...
2019-05-29 13:47:39,988 start_driver.py[line:26] INFO: start app...
2019-05-29 13:49:13,230 start_driver.py[line:26] INFO: start app...
2019-05-29 14:12:31,184 start_driver.py[line:26] INFO: start app...
2019-05-29 14:49:36,405 start_driver.py[line:26] INFO: start app...
2019-05-29 14:51:00,808 common_func.py[line:47] INFO: get login screenshot
2019-05-29 14:51:04,123 loginPage.py[line:44] INFO: login success!
2019-05-29 14:51:29,540 loginPage.py[line:58] INFO: logout success!
2019-05-29 14:51:29,540 common_func.py[line:47] INFO: get logout screenshot
2019-05-29 15:55:51,200 start_driver.py[line:26] INFO: start app...
2019-05-29 15:57:28,422 common_func.py[line:47] INFO: get login screenshot
2019-05-29 15:57:31,452 loginPage.py[line:56] INFO: login success!
2019-05-29 15:57:58,721 loginPage.py[line:70] INFO: logout success!
2019-05-29 15:57:58,721 common_func.py[line:47] INFO: get logout screenshot
2019-05-29 17:07:15,843 read_csv.py[line:19] ERROR: [Errno 2] No such file or directory: 'E:\\PythonAppium\\AppiumProject\\data\\account1.csv'
2019-05-29 17:07:53,769 read_csv.py[line:19] ERROR: list index out of range
2019-05-29 17:17:58,133 read_csv.py[line:19] INFO: There is no such data!
2019-05-29 17:17:58,133 read_csv.py[line:19] INFO: There is no such data!
2019-05-29 17:17:58,133 read_csv.py[line:19] INFO: There is no such data!
2019-05-29 17:18:12,419 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:18:12,420 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:18:12,420 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:18:21,825 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:18:21,825 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:55:11,715 getConfig.py[line:19] ERROR: No option 'host1' in section: 'email'
2019-05-29 17:55:33,510 getConfig.py[line:19] ERROR: No section: 'email1'
2019-05-30 11:19:58,670 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 11:19:58,680 start_driver.py[line:26] INFO: start app...
2019-05-30 11:20:40,564 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 11:20:45,569 start_driver.py[line:26] INFO: start app...
2019-05-30 11:24:04,642 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 11:24:04,646 start_driver.py[line:26] INFO: start app...
2019-05-30 11:24:49,246 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 11:24:54,252 start_driver.py[line:26] INFO: start app...
2019-05-30 11:32:46,182 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 11:32:46,186 start_driver.py[line:26] INFO: start app...
2019-05-30 11:33:17,780 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 11:33:22,787 start_driver.py[line:26] INFO: start app...
2019-05-30 11:35:07,408 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 11:35:07,412 start_driver.py[line:26] INFO: start app...
2019-05-30 11:35:47,731 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 11:35:52,733 start_driver.py[line:26] INFO: start app...
2019-05-30 11:37:33,237 start_driver.py[line:26] INFO: start app...
2019-05-30 11:38:39,170 start_driver.py[line:26] INFO: start app...
2019-05-30 11:41:13,699 start_driver.py[line:26] INFO: start app...
2019-05-30 11:42:46,537 common_func.py[line:47] INFO: get login screenshot
2019-05-30 11:42:49,241 loginPage.py[line:56] INFO: login success!
2019-05-30 12:27:55,370 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 12:27:55,373 start_driver.py[line:26] INFO: start app...
2019-05-30 12:28:22,715 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 12:28:27,718 start_driver.py[line:26] INFO: start app...
2019-05-30 12:58:09,297 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 12:58:09,300 start_driver.py[line:26] INFO: start app...
2019-05-30 12:58:57,146 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 13:00:03,135 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 13:00:03,137 start_driver.py[line:26] INFO: start app...
2019-05-30 13:00:53,685 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 13:02:44,049 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 13:02:44,052 start_driver.py[line:26] INFO: start app...
2019-05-30 13:04:03,747 common_func.py[line:47] INFO: get login screenshot
2019-05-30 13:04:06,191 loginPage.py[line:56] INFO: login success!
2019-05-30 13:04:08,828 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 13:50:21,969 run_test.py[line:15] INFO: start run test case！
2019-05-30 13:50:21,969 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 13:50:21,974 start_driver.py[line:26] INFO: start app...
2019-05-30 13:51:02,243 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 13:51:18,903 run_test.py[line:15] INFO: start run test case！
2019-05-30 13:51:18,903 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 13:51:18,911 start_driver.py[line:26] INFO: start app...
2019-05-30 13:52:04,628 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 14:08:36,627 run_test.py[line:15] INFO: start run test case！
2019-05-30 14:08:36,628 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 14:08:36,631 start_driver.py[line:26] INFO: start app...
2019-05-30 14:13:04,279 run_test.py[line:15] INFO: start run test case！
2019-05-30 14:13:04,279 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 14:13:04,281 start_driver.py[line:26] INFO: start app...
2019-05-30 14:13:34,529 start_driver.py[line:31] ERROR: fail to connect devices!
2019-05-30 14:13:34,531 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 14:14:18,598 run_test.py[line:15] INFO: start run test case！
2019-05-30 14:14:18,601 start_driver.py[line:26] INFO: start app...
2019-05-30 14:14:48,882 start_driver.py[line:31] ERROR: fail to connect devices!
2019-05-30 14:17:22,645 run_test.py[line:15] INFO: start run test case！
2019-05-30 14:17:22,648 start_driver.py[line:26] INFO: start app...
2019-05-30 14:21:27,810 run_test.py[line:15] INFO: start run test case！
2019-05-30 14:21:27,812 start_driver.py[line:26] INFO: start app...
2019-05-30 15:11:13,317 run_test.py[line:15] INFO: start run test case！
2019-05-30 15:11:13,320 start_driver.py[line:26] INFO: start app...
2019-05-30 15:17:40,423 run_test.py[line:15] INFO: start run test case！
2019-05-30 15:17:40,429 start_driver.py[line:26] INFO: start app...
2019-05-30 15:18:36,250 common_func.py[line:40] ERROR: 引导页滑动失败!
2019-05-30 15:24:43,367 start_driver.py[line:26] INFO: start app...
2019-05-30 15:41:10,101 run_test.py[line:15] INFO: start run test case！
2019-05-30 15:41:10,105 start_driver.py[line:26] INFO: start app...
2019-05-30 15:41:47,975 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 15:42:10,175 start_driver.py[line:26] INFO: start app...
2019-05-30 15:44:08,561 run_test.py[line:15] INFO: start run test case！
2019-05-30 15:44:08,563 start_driver.py[line:26] INFO: start app...
2019-05-30 15:46:05,751 start_driver.py[line:26] INFO: start app...
2019-05-30 15:55:59,542 run_test.py[line:15] INFO: start run test case！
2019-05-30 15:55:59,544 start_driver.py[line:26] INFO: start app...
2019-05-30 15:56:04,609 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 15:56:04,610 common_func.py[line:20] ERROR: Failed to get screen size
2019-05-30 15:56:04,610 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 15:58:44,605 run_test.py[line:15] INFO: start run test case！
2019-05-30 15:58:44,607 start_driver.py[line:26] INFO: start app...
2019-05-30 15:59:14,423 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 15:59:57,305 run_test.py[line:15] INFO: start run test case！
2019-05-30 15:59:57,310 start_driver.py[line:26] INFO: start app...
2019-05-30 16:00:49,628 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 16:01:59,279 run_test.py[line:15] INFO: start run test case！
2019-05-30 16:01:59,285 start_driver.py[line:26] INFO: start app...
2019-05-30 16:03:50,707 start_driver.py[line:26] INFO: start app...
2019-05-30 16:13:24,308 run_test.py[line:15] INFO: start run test case！
2019-05-30 16:13:24,311 start_driver.py[line:26] INFO: start app...
2019-05-30 16:13:55,486 common_func.py[line:62] ERROR: 启动失败!
2019-05-30 16:15:53,863 run_test.py[line:15] INFO: start run test case！
2019-05-30 16:15:53,867 start_driver.py[line:26] INFO: start app...
2019-05-30 16:23:14,235 run_test.py[line:15] INFO: start run test case！
2019-05-30 16:23:14,238 start_driver.py[line:26] INFO: start app...
2019-05-30 16:23:42,673 common_func.py[line:62] ERROR: 启动失败!
2019-05-30 16:24:41,537 start_driver.py[line:26] INFO: start app...
2019-05-30 16:25:34,613 common_func.py[line:62] ERROR: 启动失败!
2019-05-30 16:26:30,499 start_driver.py[line:26] INFO: start app...
2019-05-30 16:27:19,536 common_func.py[line:44] ERROR: 引导页滑动失败!
2019-05-30 16:27:19,537 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:28:09,572 start_driver.py[line:26] INFO: start app...
2019-05-30 16:29:01,012 common_func.py[line:44] ERROR: 引导页滑动失败!
2019-05-30 16:29:01,012 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:29:53,921 start_driver.py[line:26] INFO: start app...
2019-05-30 16:30:34,589 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:30:39,154 common_func.py[line:62] ERROR: 启动失败!
2019-05-30 16:31:01,870 start_driver.py[line:26] INFO: start app...
2019-05-30 16:31:45,674 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:31:54,999 common_func.py[line:62] ERROR: 启动失败!
2019-05-30 16:33:18,631 start_driver.py[line:26] INFO: start app...
2019-05-30 16:33:23,651 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 16:33:23,651 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:33:48,588 start_driver.py[line:26] INFO: start app...
2019-05-30 16:33:53,611 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 16:33:53,611 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:34:57,776 start_driver.py[line:26] INFO: start app...
2019-05-30 16:35:02,795 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 16:35:02,795 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:37:20,488 start_driver.py[line:26] INFO: start app...
2019-05-30 16:37:20,506 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 16:37:20,506 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:37:29,449 start_driver.py[line:26] INFO: start app...
2019-05-30 16:37:29,462 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 16:37:29,462 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:37:40,362 start_driver.py[line:26] INFO: start app...
2019-05-30 16:37:40,376 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 16:37:40,376 common_func.py[line:21] ERROR: Failed to get screen size
2019-05-30 16:37:40,376 common_func.py[line:44] ERROR: 引导页滑动失败!
2019-05-30 16:37:40,376 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:38:09,481 run_test.py[line:15] INFO: start run test case！
2019-05-30 16:38:09,484 start_driver.py[line:26] INFO: start app...
2019-05-30 16:38:09,497 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 16:38:09,498 common_func.py[line:21] ERROR: Failed to get screen size
2019-05-30 16:38:09,499 common_func.py[line:44] ERROR: 引导页滑动失败!
2019-05-30 16:38:56,573 start_driver.py[line:26] INFO: start app...
2019-05-30 16:39:23,567 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:40:11,410 start_driver.py[line:26] INFO: start app...
2019-05-30 16:40:53,004 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:40:58,935 common_func.py[line:63] ERROR: 启动失败!
2019-05-30 16:41:25,655 start_driver.py[line:26] INFO: start app...
2019-05-30 16:42:09,372 common_func.py[line:53] INFO: get startapp screenshot
2019-05-30 16:42:55,159 start_driver.py[line:26] INFO: start app...
2019-05-30 16:43:33,747 common_func.py[line:53] INFO: get startapp screenshot
2019-05-30 16:44:20,315 start_driver.py[line:26] INFO: start app...
2019-05-30 16:45:01,617 common_func.py[line:53] INFO: get startapp screenshot
2019-05-30 16:45:29,262 start_driver.py[line:26] INFO: start app...
2019-05-30 16:46:23,071 common_func.py[line:53] INFO: get startapp screenshot
2019-05-30 16:46:30,217 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 16:46:55,902 start_driver.py[line:26] INFO: start app...
2019-05-30 16:47:52,685 common_func.py[line:53] INFO: get startapp screenshot
2019-05-30 16:49:08,302 run_test.py[line:15] INFO: start run test case！
2019-05-30 16:49:08,305 start_driver.py[line:26] INFO: start app...
2019-05-30 16:49:43,400 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 16:50:18,155 start_driver.py[line:26] INFO: start app...
2019-05-30 16:52:06,301 start_driver.py[line:26] INFO: start app...
2019-05-30 16:52:47,653 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 16:53:30,645 start_driver.py[line:26] INFO: start app...
2019-05-30 16:54:14,283 common_func.py[line:53] INFO: get startapp screenshot
2019-05-30 16:54:51,245 run_test.py[line:15] INFO: start run test case！
2019-05-30 16:54:51,247 start_driver.py[line:26] INFO: start app...
2019-05-30 16:56:40,524 common_func.py[line:53] INFO: get login screenshot
2019-05-30 16:56:43,344 loginPage.py[line:56] INFO: login success!
2019-05-30 17:00:37,985 run_test.py[line:15] INFO: start run test case！
2019-05-30 17:00:37,989 start_driver.py[line:26] INFO: start app...
2019-05-30 17:01:37,624 start_driver.py[line:26] INFO: start app...
2019-05-30 17:02:19,350 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 17:02:39,796 start_driver.py[line:26] INFO: start app...
2019-05-30 17:03:49,224 start_driver.py[line:26] INFO: start app...
2019-05-30 17:04:45,984 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 17:44:48,837 run_test.py[line:15] INFO: start run test case！
2019-05-30 17:44:48,840 start_driver.py[line:26] INFO: start app...
2019-05-30 17:45:19,863 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 17:45:46,152 start_driver.py[line:26] INFO: start app...
2019-05-30 17:46:16,878 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 17:46:42,641 start_driver.py[line:26] INFO: start app...
2019-05-30 17:47:16,110 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 17:47:42,253 start_driver.py[line:26] INFO: start app...
2019-05-30 17:48:13,429 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 21:14:07,756 run_test.py[line:15] INFO: start run test case！
2019-05-30 21:14:20,589 start_driver.py[line:33] ERROR: fail to connect devices!
2019-05-30 21:17:10,020 start_driver.py[line:33] ERROR: fail to connect devices!
2019-05-30 21:20:57,747 start_driver.py[line:33] ERROR: fail to connect devices!
2019-05-30 21:20:57,747 common_func.py[line:53] INFO: get startapp screenshot
2019-05-30 21:21:22,022 start_driver.py[line:33] ERROR: fail to connect devices!
2019-05-30 21:21:22,022 common_func.py[line:20] ERROR: Failed to get screen size
2019-05-30 21:21:22,022 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 21:21:32,319 start_driver.py[line:33] ERROR: fail to connect devices!
2019-05-30 21:22:24,908 start_driver.py[line:33] ERROR: 'uiautomator2'
2019-05-30 21:26:18,509 start_driver.py[line:27] INFO: start app...
2019-05-30 21:28:00,280 run_test.py[line:15] INFO: start run test case！
2019-05-30 21:28:00,285 start_driver.py[line:27] INFO: start app...
2019-05-30 21:29:04,648 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:29:04,940 loginPage.py[line:56] INFO: login success!
2019-05-30 21:29:11,873 start_driver.py[line:27] INFO: start app...
2019-05-30 21:30:16,092 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:30:16,377 loginPage.py[line:56] INFO: login success!
2019-05-30 21:30:24,998 start_driver.py[line:27] INFO: start app...
2019-05-30 21:31:28,758 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:31:29,041 loginPage.py[line:56] INFO: login success!
2019-05-30 21:31:35,508 start_driver.py[line:27] INFO: start app...
2019-05-30 21:32:40,281 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:32:40,556 loginPage.py[line:56] INFO: login success!
2019-05-30 21:40:19,114 run_test.py[line:15] INFO: start run test case！
2019-05-30 21:40:19,118 start_driver.py[line:27] INFO: start app...
2019-05-30 21:41:24,706 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:41:25,638 loginPage.py[line:77] INFO: login success
2019-05-30 21:41:32,135 start_driver.py[line:27] INFO: start app...
2019-05-30 21:42:36,544 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:42:39,119 loginPage.py[line:77] INFO: login success
2019-05-30 21:42:45,858 start_driver.py[line:27] INFO: start app...
2019-05-30 21:43:50,556 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:43:51,079 loginPage.py[line:77] INFO: login success
2019-05-30 21:43:57,357 start_driver.py[line:27] INFO: start app...
2019-05-30 21:45:01,084 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:45:03,672 loginPage.py[line:77] INFO: login success
2019-05-30 22:26:44,086 run_test.py[line:15] INFO: start run test case！
2019-05-30 22:26:44,091 start_driver.py[line:27] INFO: start app...
2019-05-30 22:27:48,440 common_func.py[line:53] INFO: get login screenshot
2019-05-30 22:27:49,201 loginPage.py[line:82] INFO: login success
2019-05-30 22:27:55,497 start_driver.py[line:27] INFO: start app...
2019-05-30 22:28:58,912 common_func.py[line:53] INFO: get login screenshot
2019-05-30 22:29:01,468 loginPage.py[line:82] INFO: login success
2019-05-30 22:29:07,794 start_driver.py[line:27] INFO: start app...
2019-05-30 22:30:12,075 common_func.py[line:53] INFO: get login screenshot
2019-05-30 22:30:12,606 loginPage.py[line:82] INFO: login success
2019-05-30 22:30:18,979 start_driver.py[line:27] INFO: start app...
2019-05-30 22:31:22,428 common_func.py[line:53] INFO: get login screenshot
2019-05-30 22:31:24,991 loginPage.py[line:82] INFO: login success
2019-05-30 23:17:36,246 run_test.py[line:15] INFO: start run test case！
2019-05-30 23:17:36,251 start_driver.py[line:27] INFO: start app...
2019-05-30 23:18:40,838 common_func.py[line:53] INFO: get login screenshot
2019-05-30 23:18:55,169 loginPage.py[line:83] INFO: login success!
2019-05-30 23:19:01,470 start_driver.py[line:27] INFO: start app...
2019-05-30 23:20:05,210 common_func.py[line:53] INFO: get login screenshot
2019-05-30 23:20:20,937 loginPage.py[line:79] INFO: login fail!
2019-05-30 23:20:20,937 common_func.py[line:53] INFO: get login fail screenshot
2019-05-30 23:20:27,400 start_driver.py[line:27] INFO: start app...
2019-05-30 23:21:31,366 common_func.py[line:53] INFO: get login screenshot
2019-05-30 23:21:47,096 loginPage.py[line:79] INFO: login fail!
2019-05-30 23:21:47,096 common_func.py[line:53] INFO: get login fail screenshot
2019-05-30 23:21:53,580 start_driver.py[line:27] INFO: start app...
2019-05-30 23:22:57,584 common_func.py[line:53] INFO: get login screenshot
2019-05-30 23:23:12,926 loginPage.py[line:79] INFO: login fail!
2019-05-30 23:23:12,926 common_func.py[line:53] INFO: get login fail screenshot
